In [1]:
import pandas as pd
import numpy as np

In [2]:
NBA_dict = {'player' : ['Stephen Curry', 'Bradley Beal', 'Damian Lillard', 'Joel Embiid', 'Giannis Antetokounmpo'],
              'team' : ['GSW', 'WAS', 'POR', 'PHI', 'MIL'],
              'points/game' : [32, 31.3, 28.8, 28.5, 28.1]}

In [3]:
NBA = pd.DataFrame(NBA_dict)

In [4]:
NBA['min'] = [34.2, 35.8, 35.8, 31.1, 33]

In [5]:
NBA.loc[4,'min'] = np.NaN

In [6]:
NBA.info()  #missing value will be null in info

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   player       5 non-null      object
 1   team         5 non-null      object
 2   points/game  5 non-null      float64
 3   min          4 non-null      float64
dtypes: float64(2), object(2)
memory usage: 288.0+ bytes

In [7]:
NBA.corr()  #correlation between points/game and min

             points/game       min
points/game     1.000000  0.409936
min             0.409936  1.000000

In [8]:
NBA.cov()  #covariance between points/game and min

             points/game       min
points/game     3.163000  1.598333
min             1.598333  4.909167

In [9]:
NBA['points/game'].quantile(0.60)

29.800000000000004

In [10]:
data = pd.read_csv('Teams.csv')  #to read a csv file

In [11]:
data

     ID                    Name  Team Rank by Points   WIN%    PTS Location
0    MB         Milwaukee Bucks                    1  0.639  120.1      CEN
1    BN           Brooklyn Nets                    2  0.667  118.6      ATL
2    WW      Washington Wizards                    3  0.472  116.6      SOE
3    UJ               Utah Jazz                    4  0.722  116.4      NOR
4   PTB  Portland Trail Blazers                    5  0.583  116.1      NOR
5    IP          Indiana Pacers                    6  0.472  115.3      CEN
6    PS            Phoenix Suns                    7  0.708  115.3      PAC
7    DN          Denver Nuggets                    8  0.653  115.1      NOR
8   NOP    New Orleans Pelicans                    9  0.431  114.6      SOW
9    LC             LA Clippers                   10  0.653  114.0      PAC
10   SK        Sacramento Kings                   11  0.431  113.7      PAC
11  GSW   Golden State Warriors                   12  0.542  113.7      PAC
12   AH           Atlanta Hawks                   13  0.569  113.7      SOE
13  P76      Philadelphia 76ers                   14  0.681  113.6      ATL
14   MG       Memphis Grizzlies                   15  0.528  113.3      SOW
15   BC          Boston Celtics                   16  0.500  112.6      ATL
16   DM        Dallas Mavericks                   17  0.583  112.4      SOW
17   MT  Minnesota Timberwolves                   18  0.319  112.1      NOR
18   TR         Toronto Raptors                   19  0.375  111.3      ATL
19  SAS       San Antonio Spurs                   20  0.458  111.1      SOW
20   CB           Chicago Bulls                   21  0.431  110.7      CEN
21  LAL      Los Angeles Lakers                   22  0.583  109.5      PAC
22   CH       Charlotte Hornets                   23  0.458  109.5      SOE
23   HR         Houston Rockets                   24  0.236  108.8      SOW
24   MH              Miami Heat                   25  0.556  108.1      SOE
25  NYK         New York Knicks                   26  0.569  107.0      ATL
26   DP         Detroit Pistons                   27  0.278  106.6      CEN
27  OCT   Oklahoma City Thunder                   28  0.306  105.0      NOR
28   OM           Orlando Magic                   29  0.292  104.0      SOE
29   CC     Cleveland Cavaliers                   30  0.306  103.8      CEN

In [12]:
data2 = pd.read_csv('Teams.csv', header = None)  #to display the header row as the first row instead of header

In [13]:
data2

      0                       1                    2      3      4         5
0    ID                    Name  Team Rank by Points   WIN%    PTS  Location
1    MB         Milwaukee Bucks                    1  0.639  120.1       CEN
2    BN           Brooklyn Nets                    2  0.667  118.6       ATL
3    WW      Washington Wizards                    3  0.472  116.6       SOE
4    UJ               Utah Jazz                    4  0.722  116.4       NOR
5   PTB  Portland Trail Blazers                    5  0.583  116.1       NOR
6    IP          Indiana Pacers                    6  0.472  115.3       CEN
7    PS            Phoenix Suns                    7  0.708  115.3       PAC
8    DN          Denver Nuggets                    8  0.653  115.1       NOR
9   NOP    New Orleans Pelicans                    9  0.431  114.6       SOW
10   LC             LA Clippers                   10  0.653    114       PAC
11   SK        Sacramento Kings                   11  0.431  113.7       PAC
12  GSW   Golden State Warriors                   12  0.542  113.7       PAC
13   AH           Atlanta Hawks                   13  0.569  113.7       SOE
14  P76      Philadelphia 76ers                   14  0.681  113.6       ATL
15   MG       Memphis Grizzlies                   15  0.528  113.3       SOW
16   BC          Boston Celtics                   16    0.5  112.6       ATL
17   DM        Dallas Mavericks                   17  0.583  112.4       SOW
18   MT  Minnesota Timberwolves                   18  0.319  112.1       NOR
19   TR         Toronto Raptors                   19  0.375  111.3       ATL
20  SAS       San Antonio Spurs                   20  0.458  111.1       SOW
21   CB           Chicago Bulls                   21  0.431  110.7       CEN
22  LAL      Los Angeles Lakers                   22  0.583  109.5       PAC
23   CH       Charlotte Hornets                   23  0.458  109.5       SOE
24   HR         Houston Rockets                   24  0.236  108.8       SOW
25   MH              Miami Heat                   25  0.556  108.1       SOE
26  NYK         New York Knicks                   26  0.569    107       ATL
27   DP         Detroit Pistons                   27  0.278  106.6       CEN
28  OCT   Oklahoma City Thunder                   28  0.306    105       NOR
29   OM           Orlando Magic                   29  0.292    104       SOE
30   CC     Cleveland Cavaliers                   30  0.306  103.8       CEN

In [14]:
data2.columns

Int64Index([0, 1, 2, 3, 4, 5], dtype='int64')

In [15]:
data.columns

Index(['ID', 'Name', 'Team Rank by Points', 'WIN%', 'PTS', 'Location'], dtype='object')

In [16]:
data3 = pd.read_csv('Teams.csv', header = 0, names = ['c_1','c_2','c_3','c_4','c_5','c_6'])  #to change the column names

In [17]:
data3

    c_1                     c_2  c_3    c_4    c_5  c_6
0    MB         Milwaukee Bucks    1  0.639  120.1  CEN
1    BN           Brooklyn Nets    2  0.667  118.6  ATL
2    WW      Washington Wizards    3  0.472  116.6  SOE
3    UJ               Utah Jazz    4  0.722  116.4  NOR
4   PTB  Portland Trail Blazers    5  0.583  116.1  NOR
5    IP          Indiana Pacers    6  0.472  115.3  CEN
6    PS            Phoenix Suns    7  0.708  115.3  PAC
7    DN          Denver Nuggets    8  0.653  115.1  NOR
8   NOP    New Orleans Pelicans    9  0.431  114.6  SOW
9    LC             LA Clippers   10  0.653  114.0  PAC
10   SK        Sacramento Kings   11  0.431  113.7  PAC
11  GSW   Golden State Warriors   12  0.542  113.7  PAC
12   AH           Atlanta Hawks   13  0.569  113.7  SOE
13  P76      Philadelphia 76ers   14  0.681  113.6  ATL
14   MG       Memphis Grizzlies   15  0.528  113.3  SOW
15   BC          Boston Celtics   16  0.500  112.6  ATL
16   DM        Dallas Mavericks   17  0.583  112.4  SOW
17   MT  Minnesota Timberwolves   18  0.319  112.1  NOR
18   TR         Toronto Raptors   19  0.375  111.3  ATL
19  SAS       San Antonio Spurs   20  0.458  111.1  SOW
20   CB           Chicago Bulls   21  0.431  110.7  CEN
21  LAL      Los Angeles Lakers   22  0.583  109.5  PAC
22   CH       Charlotte Hornets   23  0.458  109.5  SOE
23   HR         Houston Rockets   24  0.236  108.8  SOW
24   MH              Miami Heat   25  0.556  108.1  SOE
25  NYK         New York Knicks   26  0.569  107.0  ATL
26   DP         Detroit Pistons   27  0.278  106.6  CEN
27  OCT   Oklahoma City Thunder   28  0.306  105.0  NOR
28   OM           Orlando Magic   29  0.292  104.0  SOE
29   CC     Cleveland Cavaliers   30  0.306  103.8  CEN

In [18]:
NBA.to_csv('NBA.csv', index = False)  #to write data into a csv file without index on the most left column